version: '3.1'
services:
    db:
        image: mysql
        container_name: microex
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root  
            MYSQL_DATABASE: microex     
        ports: 
            - "3306:3306"
        volumes: 
            - microex:/var/lib/mysql

volumes: 
  microex: