package com.sistema.macroex.model;



public enum Paises {

AFEGANISTAO("Afeganistão"),
AFRICADOSUL("África do Sul"),
ALBANIA("Albânia"),
ALEMANHA("Alemanha"),
ANDORRA("Andorra"),
ANGOLA( "Angola"),
ANGUILLA( "Anguilla"),
ANTÁRTIDA( "Antártida"),
ANTIGUAEBARBURA( "Antígua e Barbuda"),
ANTILHAHOLANDESAS( "Antilhas Holandesas"),
ARABIASAUDITA( "Arábia Saudita"),
ARGELIA( "Argélia"),
ARGENTINA( "Argentina"),
ARMENIA( "Armênia"),
ARUBA( "Aruba"),
AUSTRALIA( "Austrália"),
AUSTRIA( "Áustria"),
AZERBAIJAO( "Azerbaijão"),
BAHAMAS( "Bahamas"),
BAHNREIN( "Bahrein"),
BANGLADESH( "Bangladesh"),
BARBADOS( "Barbados"),
BELARUS( "Belarus"),
BELGICA( "Bélgica"),
BELIZE( "Belize"),
BENIN( "Benin"),
BERMUDAS( "Bermudas"),
BOLIVIA( "Bolívia"),
BOSNIA( "Bósnia-Herzegóvina"),
BOTSIANA( "Botsuana"),
BRASIL( "Brasil"),
BRUNEI( "Brunei"),
BULGARIA( "Bulgária"),
BURKINAFASSO( "Burkina Fasso"),
BURUNDI( "Burundi"),
BUTAO( "Butão"),
CABOVERDE( "Cabo Verde"),
CAMAROES( "Camarões"),
CAMBOJA( "Camboja"),
CANADA( "Canadá"),
CAZAQUISTAO( "Cazaquistão"),
CHADE( "Chade"),
Chile( "Chile"),
CHINA( "China"),
CHIPRE( "Chipre"),
CONGAPURA( "Cingapura"),
COLOMBIA( "Colômbia"),
CONGO( "Congo"),
COREIADONORTE( "Coréia do Norte"),
COREIADOSUL( "Coréia do Sul"),
CASTADOMARFIM( "Costa do Marfim"),
COSARICA( "Costa Rica"),
CORACIA( "Croácia"),
CUBA( "Cuba"),
DINAMARCA( "Dinamarca"),
DJIBUCI( "Djibuti"),
DOMINICA( "Dominica"),
EGITO( "Egito"),
ELSALVADOR( "El Salvador"),
EMIRADOS( "Emirados Árabes Unidos"),
EQUADOR( "Equador"),
ERITREIA( "Eritréia"),
ESLOVAQUIA( "Eslováquia"),
ESLOVENIA( "Eslovênia"),
ESPANHA( "Espanha"),
EUA( "Estados Unidos"),
ESTONIA( "Estônia"),
ETIOPIA( "Etiópia"),
FIJI( "Fiji"),
FILIPINAS( "Filipinas"),
FINLANDIA( "Finlândia"),
FRANCA( "França"),
GABAO( "Gabão"),
GAMBIA( "Gâmbia"),
GANA( "Gana"),
GEORGIA( "Geórgia"),
GILBRALTAR( "Gibraltar"),
GRABRETANHA( "Grã-Bretanha"),
GRANADA ("Granada"),
GRECIA( "Grécia"),
GROELANDIA( "Groelândia"),
GUADALUPE( "Guadalupe"),
GUAM( "Guam (Território dos Estados Unidos)"),
GUATEMALA( "Guatemala"),
GUERNSEY( "Guernsey"),
GUIANA( "Guiana"),
GUIANAFRANCESA( "Guiana Francesa"),
GUINE( "Guiné"),
GUINEEQUATORIAL( "Guiné Equatorial"),
GUINEBISSAU( "Guiné-Bissau"),
HAITI( "Haiti"),
HOLANDA( "Holanda"),
HONURAS( "Honduras"),
HONGKONG( "Hong Kong"),
HUNGRIA( "Hungria"),
IEMEN( "Iêmen"),
ILHABOUVET( "Ilha Bouvet"),
ILHADOHOMEM( "Ilha do Homem"),
ILHANATAL( "Ilha Natal"),
ILHAPITCAIN( "Ilha Pitcairn"),
ILHAREUNIAO( "Ilha Reunião"),
ILHASALAND( "Ilhas Aland"),
ILHASCAYMAN( "Ilhas Cayman"),
ILHACSOCOS( "Ilhas Cocos"),
ILHASCOMORES( "Ilhas Comores"),
ILHASCOOK( "Ilhas Cook"),
ILHASFAROES( "Ilhas Faroes"),
ILHAFSALKLAND( "Ilhas Falkland (Malvinas)"),
ILHASGEORGIADOSUL( "Ilhas Geórgia do Sul e Sandwich do Sul"),
ILHASHEARD( "Ilhas Heard e McDonald"),
ILHASMARIANASDONORTE( "Ilhas Marianas do Norte"),
ILHASMARSHALL( "Ilhas Marshall"),
ILHASMENORES( "Ilhas Menores dos Estados Unidos"),
ILHASNORFOLK( "Ilhas Norfolk"),
ILHASSEYHELLES( "Ilhas Seychelles"),
ILHASSALOMAO( "Ilhas Solomão"),
ILHASSVALBARD( "Ilhas Svalbard e Jan Mayen"),
ILHASTOKELAU( "Ilhas Tokelau"),
ILHASTURKUS( "Ilhas Turks e Caicos"),
ILHASVIRGENS( "Ilhas Virgens (Estados Unidos)"),
ILHASVIRGENSII( "Ilhas Virgens (Inglaterra)"),
ILHASWALLIS( "Ilhas Wallis e Futuna"),
INDIA( "índia"),
INDONESIA( "Indonésia"),
IRA( "Irã"),
IRAQUE( "Iraque"),
IRLANDIA( "Irlanda"),
ISLANDIA( "Islândia"),
IRSAEL( "Israel"),
ITALIA( "Itália"),
JAMAICA( "Jamaica"),
JAPAO( "Japão"),
JERSEY( "Jersey"),
JORDANIA( "Jordânia"),
KENIA( "Kênia"),
KIRIBATI( "Kiribati"),
KUAIT( "Kuait"),
LAOS( "Laos"),
LATVIA( "Látvia"),
LESOTO( "Lesoto"),
LIBANO( "Líbano"),
LIBERIA( "Libéria"),
LIBIA( "Líbia"),
LIECHTENSTEIN( "Liechtenstein"),
LITUANIA( "Lituânia"),
LUXEMBURGO( "Luxemburgo"),
MACAU( "Macau"),
MACEDONIA( "Macedônia"),
MADAFASCAR( "Madagascar"),
MALASIA( "Malásia"),
MALAUI( "Malaui"),
MALDIVAS( "Maldivas"),
MALI( "Mali"),
MALTA( "Malta"),
MARROCOS( "Marrocos"),
MARTINICA( "Martinica"),
MAURICIO( "Maurício"),
MAURITANIA( "Mauritânia"),
MAYOTTE( "Mayotte"),
MEXICO( "México"),
MICRONESIA( "Micronésia"),
MOCAMBIQUE( "Moçambique"),
MOLDOVA( "Moldova"),
MONACO( "Mônaco"),
MONGOLIA( "Mongólia"),
MONTENEGRO( "Montenegro"),
MONTSERRAT( "Montserrat"),
MYARMA( "Myanma"),
NAMIBIA( "Namíbia"),
NAURU( "Nauru"),
NEPAL( "Nepal"),
NICARÁGUA( "Nicarágua"),
NIGER( "Níger"),
NIGERIA( "Nigéria"),
NIUE( "Niue"),
NORUEGA( "Noruega"),
NOVACALEDONIA( "Nova Caledônia"),
NOVAZELANDIA( "Nova Zelândia"),
OMA( "Omã"),
PALAU( "Palau"),
PARAMÁ( "Panamá"),
PAPUANOVAFUINE( "Papua-Nova Guiné"),
PAQUISTAO( "Paquistão"),
PARAGUAIO( "Paraguai"),
PERU( "Peru"),
POLINESIAFANCESA( "Polinésia Francesa"),
POLONIA( "Polônia"),
PORTORICO( "Porto Rico"),
PORTUGAL( "Portugal"),
QATAR("Qatar"),
QUIRQUISTAO( "Quirguistão"),
REPUBLICACENTROAFRICANA( "República Centro-Africana"),
REPUBLICACONGO("República Democrática do Congo"),
REPUBLICADOMINICANA( "República Dominicana"),
REPUBLICATCHECA( "República Tcheca"),
ROMENIA( "Romênia"),
RUANDA( "Ruanda"),
RUSSIA( "Rússia"),
SAARAOCIDENTAL( "Saara Ocidental"),
SAINTVICENTE( "Saint Vincente e Granadinas"),
SAMOAAMERICANA( "Samoa Americana"),
SAMOAOCIDENTAL( "Samoa Ocidental"),
SANMARINO( "San Marino"),
SANTAHELENA( "Santa Helena"),
SANTALUCIA( "Santa Lúcia"),
SAOBARTOLOMEU( "São Bartolomeu"),
SAOCRISTOVAO( "São Cristóvão e Névis"),
SAOMARTIN( "São Martim"),
SAOTOMEEPRINCIPE( "São Tomé e Príncipe"),
SENEGAL( "Senegal"),
SERRALEOA( "Serra Leoa"),
SERVIA( "Sérvia"),
SRIA( "Síria"),
SOMALIA( "Somália"),
SRILANKA( "Sri Lanka"),
STPIETTE( "St. Pierre and Miquelon"),
SUAZILANDIA( "Suazilândia"),
SUDAO( "Sudão"),
SUECIA( "Suécia"),
SUICA( "Suíça"),
SURINAME( "Suriname"),
TADJIQUISTAO( "Tadjiquistão"),
TAILANDIA( "Tailândia"),
TAIWAN( "Taiwan"),
TANZANIA( "Tanzânia"),
TERRITORIOBRITANIICO( "Território Britânico do Oceano índico"),
TERRITORIODOSULFRANCA( "Territórios do Sul da França"),
TERRITORIOPALESTINOOCUPADOS( "Territórios Palestinos Ocupados"),
TIMORLESTE( "Timor Leste"),
TOGO( "Togo"),
TONGA( "Tonga"),
TRINIDADADNTOBAGO( "Trinidad and Tobago"),
TUNISIA( "Tunísia"),
TURCOMENISTAO( "Turcomenistão"),
TURQUIA( "Turquia"),
TUVALU( "Tuvalu"),
UCRANIA( "Ucrânia"),
UGANDA( "Uganda"),
URUGUAI("Uruguai"),
UZBERQUISAO( "Uzbequistão"),
VANUATU( "Vanuatu"),
VATICANO( "Vaticano"),
VENEZUELA( "Venezuela"),
VIETNA( "Vietnã"),
ZAMBIA( "Zâmbia"),
ZIMBABUE( "Zimbábue");

  private String nome;

  public String getNome() {
      return nome;
  }
  Paises(String nome) {
      this.nome = nome;
  }
    
}
